sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change
    on_failure: always
    on_start: never

language: bash

services:
  - docker

before_install:
  - gem install package_cloud
  - .travis/get_sftp_key.sh 

env:
  global:
    - ROOT=/opt/rootfs
    - JOBS=2
    - SFTP_DEPLOY_PORT="${SFTP_DEPLOY_PORT:-22}"
    - SFTP_DEPLOY_USER="${SFTP_DEPLOY_USER:-travis}"
    - SFTP_DEPLOY_ADDR="${SFTP_DEPLOY_ADDR:-empty}"
  matrix:
    - TAG=wheezy-64    CMD=run_tests
    - TAG=wheezy-64    CMD=build_deb
    - TAG=wheezy-32    CMD=build_deb
    - TAG=wheezy-armhf CMD=build_deb FLAV=posix
    - TAG=wheezy-armhf CMD=build_deb FLAV=xenomai
    - TAG=wheezy-armhf CMD=build_deb FLAV=rt_preempt
    - TAG=jessie-64    CMD=run_tests
    - TAG=jessie-64    CMD=build_deb
    - TAG=jessie-32    CMD=build_deb
    - TAG=jessie-armhf CMD=build_deb FLAV=posix
    - TAG=jessie-armhf CMD=build_deb FLAV=xenomai
    - TAG=jessie-armhf CMD=build_deb FLAV=rt_preempt

script:
  - .travis/docker_run.sh

after_success:
  - .travis/send_binaries.sh
  - .travis/upload_packagecloud.sh

after_script:
  - .travis/send_status.sh

