sudo: required

notifications:
  email: 
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d4ba176d0a87862caa8
    on_success: change
    on_failure: always
    on_start: never


language: bash

services:
- docker

env:
  global:
    - ROOT=/opt/rootfs
    - JOBS=2
  matrix:
    - TAG=wheezy-64    CMD=run_tests

script:
- .travis/docker_run.sh

